DROP TABLE IF EXISTS bhavya_provider_aco_features_final;

CREATE TABLE bhavya_provider_aco_features_final (
    id BIGSERIAL PRIMARY KEY,
    rndrng_npi BIGINT,
    rndrng_prvdr_last_org_name TEXT,
    rndrng_prvdr_first_name TEXT,
    rndrng_prvdr_city TEXT,
    rndrng_prvdr_state_abrvtn TEXT,
    rndrng_prvdr_zip5 DOUBLE PRECISION,
    rndrng_prvdr_ruca_desc TEXT,
    rndrng_prvdr_type TEXT,
    tot_hcpcs_cds BIGINT,
    tot_benes BIGINT,
    tot_srvcs DOUBLE PRECISION,
    tot_sbmtd_chrg DOUBLE PRECISION,
    tot_mdcr_alowd_amt DOUBLE PRECISION,
    tot_mdcr_pymt_amt DOUBLE PRECISION,
    tot_mdcr_stdzd_amt DOUBLE PRECISION,
    drug_data_suppressed BOOLEAN,
    drug_tot_hcpcs_cds BIGINT,
    drug_tot_benes BIGINT,
    drug_tot_srvcs DOUBLE PRECISION,
    drug_sbmtd_chrg DOUBLE PRECISION,
    drug_mdcr_alowd_amt DOUBLE PRECISION,
    drug_mdcr_pymt_amt DOUBLE PRECISION,
    drug_mdcr_stdzd_amt DOUBLE PRECISION,
    med_tot_hcpcs_cds BIGINT,
    med_tot_benes BIGINT,
    med_tot_srvcs DOUBLE PRECISION,
    med_sbmtd_chrg DOUBLE PRECISION,
    med_mdcr_alowd_amt DOUBLE PRECISION,
    med_mdcr_pymt_amt DOUBLE PRECISION,
    med_mdcr_stdzd_amt DOUBLE PRECISION,
    bene_avg_age DOUBLE PRECISION,
    bene_age_lt_65_cnt BIGINT,
    bene_age_65_74_cnt BIGINT,
    bene_age_75_84_cnt BIGINT,
    bene_age_gt_84_cnt BIGINT,
    bene_feml_cnt BIGINT,
    bene_male_cnt BIGINT,
    bene_dual_cnt BIGINT,
    bene_ndual_cnt BIGINT,
    bene_cc_bh_adhd_othcd_v1_pct DOUBLE PRECISION,
    bene_cc_bh_alcohol_drug_v1_pct DOUBLE PRECISION,
    bene_cc_bh_tobacco_v1_pct DOUBLE PRECISION,
    bene_cc_bh_alz_nonalzdem_v2_pct DOUBLE PRECISION,
    bene_cc_bh_anxiety_v1_pct DOUBLE PRECISION,
    bene_cc_bh_bipolar_v1_pct DOUBLE PRECISION,
    bene_cc_bh_mood_v2_pct DOUBLE PRECISION,
    bene_cc_bh_depress_v1_pct DOUBLE PRECISION,
    bene_cc_bh_pd_v1_pct DOUBLE PRECISION,
    bene_cc_bh_ptsd_v1_pct DOUBLE PRECISION,
    bene_cc_bh_schizo_othpsy_v1_pct DOUBLE PRECISION,
    bene_cc_ph_asthma_v2_pct DOUBLE PRECISION,
    bene_cc_ph_afib_v2_pct DOUBLE PRECISION,
    bene_cc_ph_cancer6_v2_pct DOUBLE PRECISION,
    bene_cc_ph_ckd_v2_pct DOUBLE PRECISION,
    bene_cc_ph_copd_v2_pct DOUBLE PRECISION,
    bene_cc_ph_diabetes_v2_pct DOUBLE PRECISION,
    bene_cc_ph_hf_nonihd_v2_pct DOUBLE PRECISION,
    bene_cc_ph_hyperlipidemia_v2_pct DOUBLE PRECISION,
    bene_cc_ph_hypertension_v2_pct DOUBLE PRECISION,
    bene_cc_ph_ischemicheart_v2_pct DOUBLE PRECISION,
    bene_cc_ph_osteoporosis_v2_pct DOUBLE PRECISION,
    bene_cc_ph_parkinson_v2_pct DOUBLE PRECISION,
    bene_cc_ph_arthritis_v2_pct DOUBLE PRECISION,
    bene_cc_ph_stroke_tia_v2_pct DOUBLE PRECISION,
    bene_avg_risk_scre DOUBLE PRECISION,
    year BIGINT,
    provider_name TEXT,
    performance_year DOUBLE PRECISION,
    services_per_beneficiary DOUBLE PRECISION,
    hcpcs_codes_per_beneficiary DOUBLE PRECISION,
    services_per_hcpcs DOUBLE PRECISION,
    submitted_charge_per_service DOUBLE PRECISION,
    submitted_charge_per_beneficiary DOUBLE PRECISION,
    allowed_amount_per_service DOUBLE PRECISION,
    allowed_amount_per_beneficiary DOUBLE PRECISION,
    payment_per_service DOUBLE PRECISION,
    payment_per_beneficiary DOUBLE PRECISION,
    standardized_amount_per_service DOUBLE PRECISION,
    standardized_amount_per_beneficiary DOUBLE PRECISION,
    payment_to_allowed_ratio DOUBLE PRECISION,
    drug_service_share DOUBLE PRECISION,
    drug_beneficiary_share DOUBLE PRECISION,
    drug_hcpcs_share DOUBLE PRECISION,
    drug_services_per_beneficiary DOUBLE PRECISION,
    drug_payment_per_service DOUBLE PRECISION,
    drug_payment_per_beneficiary DOUBLE PRECISION,
    drug_allowed_per_service DOUBLE PRECISION,
    medical_service_share DOUBLE PRECISION,
    medical_beneficiary_share DOUBLE PRECISION,
    medical_hcpcs_share DOUBLE PRECISION,
    medical_services_per_beneficiary DOUBLE PRECISION,
    medical_payment_per_service DOUBLE PRECISION,
    medical_payment_per_beneficiary DOUBLE PRECISION,
    medical_allowed_per_service DOUBLE PRECISION,
    female_share DOUBLE PRECISION,
    male_share DOUBLE PRECISION,
    dual_share DOUBLE PRECISION,
    nondual_share DOUBLE PRECISION,
    average_beneficiary_age DOUBLE PRECISION,
    beneficiary_risk_score DOUBLE PRECISION,
    behavioral_health_burden DOUBLE PRECISION,
    physical_health_burden DOUBLE PRECISION,
    overall_condition_burden DOUBLE PRECISION,
    behavioral_health_condition_count DOUBLE PRECISION,
    physical_health_condition_count DOUBLE PRECISION,
    high_condition_burden_count DOUBLE PRECISION,
    average_risk_score DOUBLE PRECISION,
    previous_year BIGINT,
    previous_year_beneficiaries DOUBLE PRECISION,
    previous_year_services DOUBLE PRECISION,
    previous_year_payment DOUBLE PRECISION,
    previous_year_allowed_amount DOUBLE PRECISION,
    previous_year_payment_per_service DOUBLE PRECISION,
    previous_year_services_per_beneficiary DOUBLE PRECISION,
    previous_year_payment_per_beneficiary DOUBLE PRECISION,
    previous_year_risk_score DOUBLE PRECISION,
    previous_year_condition_burden DOUBLE PRECISION,
    consecutive_year BOOLEAN,
    yoy_beneficiary_change_pct DOUBLE PRECISION,
    yoy_service_change_pct DOUBLE PRECISION,
    yoy_payment_change_pct DOUBLE PRECISION,
    yoy_allowed_amount_change_pct DOUBLE PRECISION,
    yoy_payment_per_service_change_pct DOUBLE PRECISION,
    yoy_services_per_beneficiary_change_pct DOUBLE PRECISION,
    yoy_payment_per_beneficiary_change_pct DOUBLE PRECISION,
    yoy_risk_score_change_pct DOUBLE PRECISION,
    yoy_condition_burden_change_pct DOUBLE PRECISION,
    provider_first_year DOUBLE PRECISION,
    provider_last_year DOUBLE PRECISION,
    provider_years_observed BIGINT,
    provider_history_span_years BIGINT,
    complete_5_year_history BOOLEAN,
    is_first_provider_year BOOLEAN,
    is_last_provider_year BOOLEAN,
    long_term_payment_change_pct DOUBLE PRECISION,
    long_term_service_change_pct DOUBLE PRECISION,
    long_term_beneficiary_change_pct DOUBLE PRECISION,
    long_term_payment_per_service_change_pct DOUBLE PRECISION,
    long_term_risk_score_change_pct DOUBLE PRECISION,
    long_term_condition_burden_change_pct DOUBLE PRECISION,
    service_intensity_per_beneficiary DOUBLE PRECISION,
    hcpcs_intensity_per_beneficiary DOUBLE PRECISION,
    services_per_condition_burden DOUBLE PRECISION,
    services_per_risk_score DOUBLE PRECISION,
    payment_efficiency DOUBLE PRECISION,
    standardized_payment_ratio DOUBLE PRECISION,
    payment_to_charge_ratio DOUBLE PRECISION,
    allowed_to_charge_ratio DOUBLE PRECISION,
    payment_vs_standardized_difference DOUBLE PRECISION,
    payment_vs_standardized_pct DOUBLE PRECISION,
    risk_adjusted_services DOUBLE PRECISION,
    risk_adjusted_payment DOUBLE PRECISION,
    risk_adjusted_allowed_amount DOUBLE PRECISION,
    condition_adjusted_payment DOUBLE PRECISION,
    condition_adjusted_services DOUBLE PRECISION,
    payment_per_risk_adjusted_beneficiary DOUBLE PRECISION,
    allowed_per_risk_adjusted_beneficiary DOUBLE PRECISION,
    medical_payment_per_service_1 DOUBLE PRECISION,
    medical_allowed_per_service_1 DOUBLE PRECISION,
    medical_payment_per_beneficiary_1 DOUBLE PRECISION,
    drug_payment_per_service_stage4 DOUBLE PRECISION,
    drug_allowed_per_service_stage4 DOUBLE PRECISION,
    drug_payment_per_beneficiary_stage4 DOUBLE PRECISION,
    medical_payment_share DOUBLE PRECISION,
    drug_payment_share DOUBLE PRECISION,
    medical_service_share_stage4 DOUBLE PRECISION,
    drug_service_share_stage4 DOUBLE PRECISION,
    performance_payment_trend DOUBLE PRECISION,
    performance_service_trend DOUBLE PRECISION,
    performance_beneficiary_trend DOUBLE PRECISION,
    performance_payment_per_service_trend DOUBLE PRECISION,
    performance_risk_trend DOUBLE PRECISION,
    aco_id TEXT,
    service_intensity_per_beneficiary_percentile DOUBLE PRECISION,
    risk_adjusted_services_percentile DOUBLE PRECISION,
    risk_adjusted_payment_percentile DOUBLE PRECISION,
    condition_adjusted_services_percentile DOUBLE PRECISION,
    condition_adjusted_payment_percentile DOUBLE PRECISION,
    payment_per_beneficiary_percentile DOUBLE PRECISION,
    payment_per_service_percentile DOUBLE PRECISION,
    utilization_score DOUBLE PRECISION,
    cost_score DOUBLE PRECISION,
    provider_segment TEXT,
    high_utilization_flag BOOLEAN,
    high_cost_flag BOOLEAN,
    low_utilization_flag BOOLEAN,
    low_cost_flag BOOLEAN,
    longitudinal_years_observed BIGINT,
    longitudinal_first_year BIGINT,
    longitudinal_last_year BIGINT,
    dominant_provider_segment TEXT,
    segment_year_count BIGINT,
    segment_stability DOUBLE PRECISION,
    overall_provider_segment TEXT,
    history_class TEXT
);

CREATE INDEX idx_bhavya_provider_npi ON bhavya_provider_aco_features_final (rndrng_npi);

CREATE INDEX idx_bhavya_provider_year ON bhavya_provider_aco_features_final (year);

CREATE INDEX idx_bhavya_provider_aco ON bhavya_provider_aco_features_final (aco_id);

CREATE INDEX idx_bhavya_provider_npi_year ON bhavya_provider_aco_features_final (rndrng_npi, year);